### ISSUE TITLE
Broken build?

### ISSUE THREAD

**Issue by dventimihasura** [pgspider/jdbc_fdw#11]
Hello,

Perhaps I'm missing something, but when I try to build this--really, when I try any of the make commands--there are these errors:

```shell
make clean
Makefile:49: /contrib/contrib-global.mk: No such file or directory
make: *** No rule to make target '/contrib/contrib-global.mk'.  Stop.
```

All these related projects seem to depend on Makefile includes like `Makfile.global` and `contrib-global.mk` that aren't in the project.  What am I doing wrong?

I also tried installing PGXS *and* `x86_64-conda-linux-gnu-cc` and building with PGXS, but that gives a different error:

```shell
USE_PGXS=true make
...
...
jq.c: In function 'jq_iterate':
jq.c:699:87: error: 'List' has no member named 'elements'
```

Thanks!

**Comment by dventimihasura** [comment]
Nevermind. I think I figured it out.

**Comment by RavazziniAndrea** [comment]
How? I'm facing the same issue..

**Comment by dventimihasura** [comment]
Evidently, you have to use [PGXS](https://www.postgresql.org/docs/current/extend-pgxs.html) which kinda makes sense if you think about it, though I do wish that was spelled out a little better:

```shell
make USE_PGXS=1
make install USE_PGXS=1
```

That may not be the cause of your problems, but it was the cause of mine.  You can see this in a Dockerfile I have [here](https://github.com/dventimihasura/hasura-projects/blob/38d52113bd19b37bb598b52ac35ba110c1fd1038/postgres-read-through-cache-1/Dockerfile)

**Comment by khieuvm** [comment]
Hello @dventimihasura,

I do not face your issue.
Could you explain more about your issue?
If this issue did not happen anymore, I think we should close this issue.

**Comment by dventimihasura** [comment]
Hi @khieuvm I don't have an issue any longer.  I just didn't understand that I needed to set a make variable with `USE_PGXS=1`.  After I did that, it worked fine.
