### ISSUE TITLE
CREATE EXTENSION failure

### ISSUE THREAD

**Issue by grouchobear** [pgspider/jdbc_fdw#21]
I'm reluctant to post this issue as I'm fairly confident that the solution is really basic.
By following the instructions here, I've been able to create jdbc_fdw.so:
/usr/lib/postgresql/14/lib/jdbc_fdw.so

I've created the symlink libjvm.so as well:
**sudo ln -s -f /usr/lib/jvm/java-11-oracle/lib/server/libjvm.so /usr/lib64/libjvm.so**

I've further insured that the path to libjvm.so is in LD_LIBRARY_PATH:
**echo $LD_LIBRARY_PATH 
/usr/lib64:/usr/lib/jvm/java-11-oracle/lib/server**
 
The problem I'm having is that when I attempt to execute CREATE EXTENSION jdbc_fdw; in psql I receive the following error:
**CREATE EXTENSION jdbc_fdw;
ERROR:  could not load library "/usr/lib/postgresql/14/lib/jdbc_fdw.so": libjvm.so: cannot open shared object file: No such file or directory**

Linux isn't my forte so it could be that there's something really basic I'm just overlooking but I'd appreciate any suggestions as to what  I can do to correct this issue.

**Comment by cntwelve** [comment]
try to ln to /usr/lib

**Comment by grouchobear** [comment]
> try to ln to /usr/lib

Awesome.  That did the trick.  Thanks.
