### ISSUE TITLE
Arbitrary SQL query execution via function that RETURNS SETOF RECORD

### ISSUE THREAD

**Issue by igor-suhorukov** [pgspider/jdbc_fdw#7]
Sometime required advanced optimization and unsupported pushdown for filtering, tables joining, aggregation/windows function results from DB behind jdbc connection. This technique works for me with fdw+dblink for PG database but dblink support it only for database that support PG wire protocol.

Please implement "table" function in jdbc_fdw with sql query parameter and "RETURNS SETOF RECORD" result

As temporary workaround I implement j[dbc function for PL/Java ](https://github.com/igor-suhorukov/pg_jdbc_bridge/blob/master/src/main/java/com/github/isuhorukov/jdbc/bridge/JdbcQuery.java)

**Comment by nxhai98** [comment]
Hello @igor-suhorukov,

Thank for your suggestion.

Currently we are planning to implement a function like `dblink(text connname, text sql [, bool fail_on_error]) returns setof record` on jdbc_fdw.

Here is this function specification:
```sql
-- jdbc_exec(text severname, text sql) returns setof record
SELECT jdbc_exec(jdbc_svr, 'SELECT * FROM tbl');
 a | b |     c      
---+---+------------
 1 | i | {a1,b1,c1}
 2 | j | {a2,b2,c2}
```
Is this function same as your expectation?

**Comment by igor-suhorukov** [comment]
Hello @nxhai98 
Yes, exactly this functionality!!!

**Comment by jopoly** [comment]
Hello @igor-suhorukov 
We finished implementing this function.

You may check our implementation in commit: https://github.com/pgspider/jdbc_fdw/commit/cc92e2613e128633aa5ba5a6eeeecd33e05f10d8
And the usage is here: https://github.com/pgspider/jdbc_fdw#arbitrary-sql-query-execution-via-function-1

We would like to hear your comment.
Thank you.

**Comment by igor-suhorukov** [comment]
@jopoly sorry for late response. I was busy with my [PgConf2023 report](https://pgconf.ru/en/2023/345870).

First of all I update my PG up to 15 version in [Docker file](https://github.com/igor-suhorukov/openstreetmap_h3/blob/master/postgis_docker-master/Dockerfile). After that I try create extension with "CREATE EXTENSION jdbc_fdw;"  

 `2023-04-06 19:58:12.012 UTC [36] ERROR:  could not load library "/usr/lib/postgresql/15/lib/jdbc_fdw.so": libjvm.so: cannot open shared object file: No such file or directory`

**Comment by nxhai98** [comment]
Hi @igor-suhorukov,

I checked your docker image, the jdbc_fdw dynamic lib was not linked to libjvm.so:
```
root@ddcbfa3f27d8:/home/jdbc_fwd# ldd jdbc_fdw.so
        linux-vdso.so.1 (0x00007ffeaddc9000)
        libpq.so.5 => /usr/lib/x86_64-linux-gnu/libpq.so.5 (0x00007f08fc043000)
        libjvm.so => not found
```
I see that all almost other libs has linked to `/usr/lib/x86_64-linux-gnu` instead of `/usr/lib64` as you do with libjvm.so.
I recreate the symbolic link of libjvm.so on `/usr/lib/x86_64-linux-gnu` and jdbc_fdw can work now:
```
root@bc3b93bb20e7:/home/jdbc_fwd# ln -s /usr/lib/jvm/java-11-openjdk-amd64/lib/server/libjvm.so /usr/lib/x86_64-linux-gnu/libjvm.so
root@bc3b93bb20e7:/home/jdbc_fwd# ldd jdbc_fdw.so
        linux-vdso.so.1 (0x00007ffde41d3000)
        libpq.so.5 => /usr/lib/x86_64-linux-gnu/libpq.so.5 (0x00007fe4bd7ec000)
        libjvm.so => /usr/lib/x86_64-linux-gnu/libjvm.so (0x00007fe4bc552000)
...
postgres@bc3b93bb20e7:/home/jdbc_fwd$ PATH=/home/vagrant/workplace/postgres/postgresql-15.2/install/bin/:$PATH psql
psql (15.2 (Debian 15.2-1.pgdg110+1))
Type "help" for help.

postgres=# create extension jdbc_fdw ;
CREATE EXTENSION
```
Could you try this?

FYI: please carefully when build jdbc_fdw, the version of `javac` and java environment `libjvm.so` should be match.

**Comment by igor-suhorukov** [comment]
@nxhai98 thank you for assistance! Now it builds successfully
```
🧐 🐘 postgres_dba 6.0 installed. Use ":dba" to see menu
Timing is on.
psql (14.7 (Ubuntu 14.7-1.pgdg20.04+1), server 15.2 (Debian 15.2-1.pgdg110+1))
Type "help" for help.

osmworld=# CREATE SERVER duckdb_srv FOREIGN DATA WRAPPER jdbc_fdw OPTIONS(
drivername 'org.duckdb.DuckDBDriver',
url 'jdbc:duckdb:',
jarfile '/input/duckdb_jdbc-0.7.1.jar',
querytimeout '10000',
maxheapsize '512Mb'
);
CREATE SERVER
Time: 6,745 ms
osmworld=# CREATE USER MAPPING FOR CURRENT_USER SERVER duckdb_srv  OPTIONS(username 'user',password 'ignoreIt');
CREATE USER MAPPING
Time: 8,595 ms
osmworld=# SELECT jdbc_exec('duckdb_srv', $$select version() $$);
 jdbc_exec 
-----------
 (v0.7.1)
(1 row)

Time: 249,160 ms
osmworld=# SELECT jdbc_exec('duckdb_srv', $$select * from '/input/simple.parquet'$$);
 jdbc_exec 
-----------
 (1,foo)
 (2,foo)
 (3,foo)
(3 rows)

Time: 5,139 ms

```
It is foundation for best journey with jdbc_exec !!!
